name: DSpot CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn install -DskipTests
      - name: Test and Coverage with Maven
        run: |
          export MAVEN_HOME=$(mvn --version | grep "Maven home" | cut -f 3 -d " ")
          cd dspot && mvn test jacoco:report
      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
